FROM node:lts as builder

# Set the working directory inside the container
WORKDIR /app

COPY webui webui

WORKDIR /app/webui

RUN npm install

RUN npm run build-prod

FROM nginx:stable

COPY --from=builder /app/webui/dist /usr/share/nginx/html
